module.exports = {
  purge: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  darkMode: false,
  content: ['./src/**/*.{html,js,jsx,ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        mulish: ['Mulish', 'sans-serif'],
        'source-sans': ['Source Sans Pro', 'sans-serif'],
      },
      fontSize: {
        xs: '0.75rem',
        sm: '0.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '2.875rem',
        '4xl': '2.25rem',
        '5xl': '3rem',
        '6xl': '4rem',
        '7xl': '5rem',
        '8xl': '4.75rem',
        '14px': '0.875rem',
        '16px': '1rem',
        '18px': '1.125rem',
        '24px': '1.5rem',
        '22px': '1.375rem',
        '28px': '1.75rem',
        '46px': '2.875rem',
        normal: '1rem',
        '66px': '4.125rem',
        '30px': '1.875rem',
        '32px': '2rem',
        '34px': '2.125rem',
        '36px': '2.25rem',
        '38px': '2.375rem',
        '40px': '2.5rem',
        '42px': '2.625rem',
        '44px': '2.75rem',
        '48px': '3rem',
        '50px': '3.125rem',
        '52px': '3.25rem',
        '54px': '3.375rem',
        '56px': '3.5rem',
        '58px': '3.625rem',
        '60px': '3.75rem',
        '68px': '4.25rem',
        '70px': '4.375rem',
        '72px': '4.5rem',
        '74px': '4.625rem',
        '76px': '4.75rem',
      },
      lineHeight: {
        normal: '1.5',
        '3.625': '3.625rem',
        '8xl': '5rem',
        '80px': '80px',
        '17.6px': '1.1rem',
        '20px': '1.25rem',
        '21px': '1.3125rem',
        '26px': '1.625rem',
        '30px': '1.875rem',
        '32px': '2rem',
        '34px': '2.125rem',
        '36px': '2.25rem',
        '38px': '2.375rem',
        '40px': '2.5rem',
        '42px': '2.625rem',
        '44px': '2.75rem',
        '46px': '2.875rem',
        '48px': '3rem',
        '50px': '3.125rem',
        '22px': '1.375rem',
      },
      fontWeight: {
        normal: '400',
        medium: '500',
        bold: '700',
        '600': '600',
      },
      spacing: {
        '1/3': '33.333%',
        '1/4': '25%',
        '1/2': '50%',
        '3/4': '75%',
        'top-12': '3rem',
        'top-16': '4rem',
        'top-32': '8rem',
        'top-48': '12rem',
        'top-64': '16rem',
        'top-80': '20rem',
        'top-96': '24rem',
        'left-10': '2.5rem',
        'left-1/2': '50%',
        '90': '90px',
        '100': '100px',
        '-72px': '-72px',
        '-10px': '-10px',
        '-60px': '-60px',
        '200px': '200px',
      },
      padding: {
        'aboutpage-140-180': '140px 0 180px',
        'about-120': '120px 0',
      },
      keyframes: {
        rotate: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
      },
      animation: {
        'identifier': 'rotate 10s linear infinite',
      },
      letterSpacing: {
        normal: '0.015em',
      },
      colors: {
        // Text colors
        'black-text': 'var(--black-text)',
        'while-text': 'var(--while-text)',
        'blue-text': 'var(--blue-text)',
        'orange-text': 'var(--orange-text)',
        'green-text': 'var(--green-text)',
        'grey-text': 'var(--grey-text)',

        // Status colors
        'red-status': 'var(--red-status)',
        'blue-status': 'var(--blue-status)',
        'green-status': 'var(--green-statu)',

        // Background colors
        'background-1': 'var(--background-1)',
        'background-2': 'var(--background-2)',
        'background-3': 'var(--background-3)',
        'background-4': 'var(--background-4)',
        'background-5': 'var(--background-5)',
        'background-6': 'var(--background-6)',
        'background-7': 'var(--background-7)',
        'background-8': 'var(--background-8)',

        'background-gray': 'var(--background-gray)',
        'background-orange-1': 'var(--background-orange-1)',
        'background-orange-2': 'var(--background-orange-2)',
        'background-orange-3': 'var(--background-orange-3)',
        'background-blue-1': 'var(--background-blue-1)',
        'background-blue-2': 'var(--background-blue-2)',
        'background-blue-3': 'var(--background-blue-3)',
        'background-green': 'var(--background-green)',
        'background-while': 'var(--background-while)',
        'background-input': 'var(--background-input)',

        // Border colors
        'border-orange': 'var(--border-orange)',

        // Icon colors
        'icon-color': 'var(--icon-color)',

        // User colors
        'user-color': 'var(--user-color)',
      },
      backgroundImage: {
        'br-gradient-top-or': 'linear-gradient(to top, var(--background-1), var(--background-2))',
        'br-gradient-right-or': 'linear-gradient(to right, var(--background-2), var(--background-1))',
        'br-gradient-sheeet': 'linear-gradient(to right, var(--background-3), var(--background-4))',
        'br-gradient-blue': 'linear-gradient(to right, var(--background-5), var(--background-6))',
        'br-gradient-green': 'linear-gradient(to right, var(--background-8), var(--background-7))',
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
